apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  progressDeadlineSeconds: 600
  replicas: {{.Values.springboot.replicas}}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{.Values.name}}"
    spec:
      containers:
      - image: "{{.Values.springboot.imageName}}:{{.Values.springboot.imageTag}}"
        env:
          - name: JASPERREPORTS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: {{.Values.springboot.secretName}}-{{.Values.namespace}}
        imagePullPolicy: Always
        name: "{{.Values.name}}"
        command: 
        - bash
        - -c
        - java -jar demo.jar; sleep 365d
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{.Values.name}}
      serviceAccountName: {{.Values.name}}
      terminationGracePeriodSeconds: 30
