# apiVersion: v1
# kind: Service
# metadata:
#   name: {{.Values.name}}
#   namespace: {{.Values.namespace}}
# spec:
#   selector:
#     app: {{.Values.name}}
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: {{ .Values.petclinic.port }}
#       targetPort: {{.Values.petclinic.port}}
#       protocol: TCP
